@startuml

class Role
class Subject
class Permission
class Operation

Role "*" - "*" Permission
Role "*" -down- "*" Subject
Permission "*" -right- "*" Operation
@enduml


abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayLis {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}
